apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "netdeploy.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "netdeploy.labels" . | nindent 4 }}
    app.kubernetes.io/component: config
data:
  {{- range $key, $value := .Values.api.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
